[build]
builder = "nixpacks"
buildCommand = "composer install"

[deploy]
postDeployCommand = "php artisan migrate --force"

startCommand = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
