[build]
builder = "nixpacks"
# buildCommand = "composer install" # Biarkan Nixpacks menangani instalasi Composer

[deploy]
preStartCommand = "php artisan config:cache && php artisan route:cache"
postDeployCommand = "php artisan db:seed --force" # Dijalankan sekali setelah deployment
startCommand = "chmod -R 775 storage bootstrap/cache || true && php artisan storage:link && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"